% Ver2.0 (01-Dec-2021)
SubjectNames = {'01','02'};   % replace 01,02, ... to proper subject names
BadChannels = {'ch00','ch01'}    % replace ch01,ch02, ... to proper sensor names


% --------------- modify above variables ------------------

sFiles = {};
N = numel(SubjectNames);
bst_report('Start', sFiles);
for I = 1:N
    % Process: Select data files in: SubjectNames[]
    sFiles = bst_process('CallProcess', 'process_select_files_data', sFiles, [], ...
        'subjectname',   SubjectNames{I}, ...
        'condition',     '', ...
        'includebad',    0, ...
        'includeintra',  0, ...
        'includecommon', 0);

    if ~isempty(BadChannels)
        % Process: Set bad channels
        sFiles = bst_process('CallProcess', 'process_channel_setbad', sFiles, [], ...
            'sensortypes', BadChannels);
    end

    % Process: Low-pass:250Hz
    sFiles = bst_process('CallProcess', 'process_bandpass', sFiles, [], ...
        'highpass',    0, ...
        'lowpass',     250, ...
        'tranband',    0, ...
        'attenuation', 'strict', ...  % 60dB
        'ver',         '2019', ...  % 2019
        'mirror',      0);

    % Process: Resample: 500Hz
    sFiles = bst_process('CallProcess', 'process_resample', sFiles, [], ...
        'freq', 500);

    % Process: Notch filter: 60Hz 120Hz 180Hz
    sFiles = bst_process('CallProcess', 'process_notch', sFiles, [], ...
        'sensortypes', 'MEG, EEG', ...
        'freqlist',    [60, 120, 180], ...
        'cutoffW',     1, ...
        'useold',      0, ...
        'read_all',    0);

    % Process: Band-pass:0.5Hz-100Hz
    sFiles = bst_process('CallProcess', 'process_bandpass', sFiles, [], ...
        'sensortypes', 'MEG, EEG', ...
        'highpass',    0.5, ...
        'lowpass',     100, ...
        'tranband',    0, ...
        'attenuation', 'strict', ...  % 60dB
        'ver',         '2019', ...  % 2019
        'mirror',      0, ...
        'read_all',    0);

    % Process: ICA components: Infomax
    sFiles = bst_process('CallProcess', 'process_ica', sFiles, [], ...
        'timewindow',   [], ...
        'eventname',    '', ...
        'eventtime',    [-0.2, 0.2], ...
        'resample',     0, ...
        'bandpass',     [0, 0], ...
        'nicacomp',     20, ...
        'sensortypes',  'MEG', ...
        'icasort',      '', ...
        'usessp',       0, ...
        'ignorebad',    1, ...
        'saveerp',      0, ...
        'method',       1);  % Infomax:    EEGLAB / RunICA
end

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);
% bst_report('Export', ReportFile, ExportDir);
